### ISSUE TITLE
Address change confirmation email does not display information

### ISSUE THREAD

**Issue by ninjagirl3691** [PageOfPages/AmericanWater#3]
TC-4, TC-5
When the user inputs and confirms new address information, the email received does not display information regarding what the new address is. Supposed to display changes.

Expected results:
Once the address changes are submitting successfully, the user should receive an email with a link and with the changes to the address displayed below. 

Steps to reproduce:
Submit address changes, check and open received email. The address information does not load but link is present.

Additional info:
The only issue is the information not displaying, should be simple to fix in code that generates the email.

**Comment by PageOfPages** [comment]
The confirmation email now displays the updated address information.
