### ISSUE TITLE
Address changes saved to database before the email is confirmed

### ISSUE THREAD

**Issue by ninjagirl3691** [PageOfPages/AmericanWater#4]
TC-5
The database updates the address before the user confirms via email.

Expected results:
The database should maintain the previously stored address until the link sent via email is clicked and the address change is confirmed.

Steps to reproduce:
User inputs address change, email link is not clicked (therefore not confirmed), address change is still saved to the database.

Additional info:
Check where in the code the address overwrite takes place, and make sure it only updates after the link is confirmed.

**Comment by PageOfPages** [comment]
Address now only updates once a user has opened the confirmation link sent to their email account.
